# Generated by Django 4.1.4 on 2023-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorpredApp', '0002_savecolors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecolors',
            name='colors',
            field=models.TextField(),
        ),
    ]
