# Generated by Django 4.1.4 on 2023-10-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_alter_usermanagementmodel_usehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagementmodel',
            name='password',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
