# Generated by Django 4.1.4 on 2023-10-30 07:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_usermanagementmodel_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagementmodel',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=8),
        ),
        migrations.AddField(
            model_name='usermanagementmodel',
            name='overlay',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
