# Generated by Django 4.1.4 on 2023-10-30 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_usermanagementmodel_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='overlay',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='usehistory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=8),
        ),
    ]
