# Generated by Django 4.1.4 on 2023-10-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_alter_usermanagementmodel_overlay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagementmodel',
            name='overlay',
        ),
    ]
