# Generated by Django 4.1.4 on 2023-10-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_usermanagementmodel_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagementmodel',
            name='fontconfig',
            field=models.JSONField(default=dict),
        ),
    ]
