# Generated by Django 4.1.4 on 2023-10-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0002_alter_audiobook_author_alter_audiobook_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='nameurl',
            field=models.CharField(default='https://res.cloudinary.com/dmfljlyu1/video/upload/v1698725247/MyImages/srilankwenithi_azfaex.mp3', max_length=300),
            preserve_default=False,
        ),
    ]
